version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "wallet-service"
      POSTGRES_USER: "dayadanya"
      POSTGRES_PASSWORD: "dayadanya"
    ports:
      - "5432:5432"